(function (root) {
  'use strict';
  const Engine = root.ProfitabilityEngine;
  const state = { rows: [], result: null, mapping: {}, fileName: '', periodStart: '', periodEnd: '', costMode: 'positive', query: '', profitability: 'all', health: 'all', leak: 'all', marketplace: 'all', sort: { key: 'totalSales', direction: 'desc' }, page: 1, pageSize: 25, charts: [] };
  const labels = { sku:'SKU', asin:'ASIN', productName:'产品名称', marketplace:'Marketplace', unitsSold:'销量', totalSales:'总销售额', adSales:'广告销售额', adSpend:'广告花费', productCost:'产品成本', fbaFees:'FBA费用', referralFees:'销售佣金', storageFees:'仓储费', returnCost:'退货成本', otherCosts:'其他成本' };
  const money = v => v == null ? '—' : Number(v).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const pct = v => v == null ? 'N/A' : `${Number(v).toFixed(2)}%`;
  const el = (tag, cls, value) => { const n = document.createElement(tag); if (cls) n.className = cls; if (value != null) n.textContent = value; return n; };

  function markup() {
    return `<section class="profitability-page">
      <header class="profitability-hero"><div><p>ADVERTISING &amp; PROFITABILITY</p><h1>广告与利润分析</h1><span>用多 SKU 经营数据识别广告效率、真实利润表现与可量化利润流失。</span></div><div class="privacy-badge">🔒 经营数据仅在当前浏览器本地解析，不会上传到服务器。</div></header>
      <section class="pf-card"><div class="pf-heading"><b>00</b><div><h2>分析周期</h2><p>经营指标必须结合明确周期阅读。</p></div></div><div class="period-grid"><label>开始日期<input id="pfPeriodStart" type="date"></label><label>结束日期<input id="pfPeriodEnd" type="date"></label><label>成本负值口径<select id="pfCostMode"><option value="positive">Positive Cost（负数转为正向成本并警告）</option><option value="signed">Signed Value（保留有符号值并警告）</option></select></label></div></section>
      <section class="pf-card"><div class="pf-heading"><b>01</b><div><h2>数据导入</h2><p>上传一份 SKU Profitability CSV；刷新页面后原始数据自动消失。</p></div><button id="pfTemplate" class="pf-button secondary">下载 CSV 模板</button></div><button id="pfDrop" class="pf-drop"><strong>点击上传或拖放 CSV 文件</strong><span>至少需要 SKU 与 Total Sales</span><small id="pfFile">尚未选择文件</small></button><input id="pfInput" type="file" accept=".csv,text/csv" hidden><div id="pfMapping"></div><button id="pfReset" class="pf-button danger" hidden>清空经营数据</button></section>
      <div id="pfEmpty" class="pf-empty"><strong>上传 SKU 利润数据开始分析</strong><span>尚无数据时不显示误导性的 $0 或 0%。</span></div>
      <div id="pfResults" hidden>
        <section class="pf-card"><div class="pf-heading"><b>02</b><div><h2>经营总览</h2><p>组合百分比按汇总金额重新计算，不平均 SKU 百分比。</p></div></div><div id="pfSummary" class="pf-metrics"></div></section>
        <section class="pf-card"><div class="pf-heading"><b>03</b><div><h2>广告健康度</h2><p>ACoS 衡量广告本身效率；TACoS 衡量整个 SKU 对广告的依赖程度。</p></div></div><div id="pfHealth" class="pf-health"></div></section>
        <section class="pf-card"><div class="pf-heading"><b>04</b><div><h2>SKU 利润明细</h2><p>金额保持各 SKU 所属 Marketplace Currency，不在计算引擎内混合换算。</p></div></div><div id="pfQuality" class="pf-quality"></div><div class="pf-filters"><input id="pfSearch" type="search" placeholder="搜索 SKU / ASIN / 产品名称"><select id="pfMarketplace"><option value="all">全部 Marketplace</option></select><select id="pfProfitFilter"><option value="all">全部盈利状态</option><option value="strong">Strong</option><option value="healthy">Healthy</option><option value="low">Low Margin</option><option value="loss">Loss</option><option value="unknown">Unknown</option></select><select id="pfHealthFilter"><option value="all">全部广告健康度</option><option value="healthy">Healthy</option><option value="warning">Warning</option><option value="critical">Critical</option><option value="no-ads">No Ads</option><option value="no-data">No Data</option></select><select id="pfLeakFilter"><option value="all">全部 Profit Leak</option><option value="advertising">广告超支</option><option value="negative-margin">当前亏损</option><option value="high-tacos">广告依赖较高</option><option value="low-margin">利润缓冲较低</option><option value="fee-burden">平台费用占比较高</option><option value="return">退货成本偏高</option></select></div><div class="pf-table-wrap"><table><thead><tr id="pfHead"></tr></thead><tbody id="pfBody"></tbody></table></div><div id="pfPager" class="pf-pager"></div></section>
        <section class="pf-card"><div class="pf-heading"><b>05</b><div><h2>Profit Leak</h2><p>规则引擎仅识别可量化或高概率利润风险，不代表完整财务审计。</p></div></div><div id="pfLeakOverview" class="pf-metrics four"></div></section>
        <section class="pf-card"><div class="pf-heading"><b>06</b><div><h2>图表分析</h2><p>优先展示收入/利润与 ACoS 盈亏线。</p></div></div><div class="pf-charts"><article><h3>Revenue vs Net Profit by SKU</h3><canvas id="pfRevenueChart"></canvas></article><article><h3>ACoS vs Break-even ACoS</h3><canvas id="pfAcosChart"></canvas></article><article><h3>TACoS Distribution</h3><canvas id="pfTacosChart"></canvas></article></div></section>
        <section class="pf-card"><div class="pf-heading"><b>07</b><div><h2>公式与数据口径</h2><p>本模块分析历史周期汇总数据，与单件前向利润模拟器口径独立。</p></div></div><div class="pf-formulas"><p><b>Organic Sales</b>max(0, Total Sales − Ad Sales)</p><p><b>ACoS</b>Ad Spend ÷ Ad Sales；无广告归因销售时显示 N/A。</p><p><b>TACoS</b>Ad Spend ÷ Total Sales。</p><p><b>Net Profit</b>Total Sales − Operating Costs − Ad Spend。</p><p><b>Net Margin</b>Net Profit ÷ Total Sales。</p><p><b>Break-even ACoS</b>Profit Before Ads ÷ Ad Sales。</p><p><b>Ad Sales Share</b>Ad Sales ÷ Total Sales。</p><p><b>Organic Sales Share</b>Organic Sales ÷ Total Sales。</p><p><b>Advertising Leak</b>max(0, Ad Spend − Ad Sales × Break-even ACoS)。</p></div><div class="pf-note">广告利润为基于整体广告前贡献利润率的估算值；数据不完整时会标记“部分成本口径”，请勿视为审计结论。</div></section>
      </div></section>`;
  }

  function parseFile(file) {
    if (!root.Papa) return alert('CSV 解析组件未加载，请刷新后重试。');
    root.Papa.parse(file, { header: true, skipEmptyLines: true, complete: data => { state.rows = data.data; state.fileName = file.name; const detected = Engine.detectMapping(data.meta.fields || Object.keys(data.data[0] || {})); state.mapping = detected.mapping; document.querySelector('#pfFile').textContent = `✓ ${file.name} · ${data.data.length} 行`; detected.missing.length ? renderMapping(data.meta.fields || []) : run(); }, error: err => alert(`CSV 解析失败：${err.message}`) });
  }

  function renderMapping(headers) {
    const host = document.querySelector('#pfMapping'); host.replaceChildren();
    const box = el('div', 'pf-map'); box.append(el('strong', '', '需要确认字段映射'));
    Object.keys(labels).forEach(field => { const label = el('label'); label.append(el('span', '', labels[field])); const select = el('select'); select.dataset.field = field; select.append(new Option('未提供', '')); headers.forEach(h => select.append(new Option(h, h))); select.value = state.mapping[field] || ''; label.append(select); box.append(label); });
    const apply = el('button', 'pf-button', '应用字段映射'); apply.type = 'button'; apply.onclick = () => { box.querySelectorAll('select').forEach(s => state.mapping[s.dataset.field] = s.value || null); run(); }; box.append(apply); host.append(box);
  }

  function run() {
    state.result = Engine.analyze({ rows: state.rows, mapping: state.mapping, costMode: state.costMode });
    if (!state.result.ok) return renderMapping(state.result.detected.headers);
    document.querySelector('#pfMapping').replaceChildren(); document.querySelector('#pfEmpty').hidden = true; document.querySelector('#pfResults').hidden = false; document.querySelector('#pfReset').hidden = false;
    renderSummary(); renderHealth(); renderQuality(); updateMarketplaces(); renderTable(); renderLeaks(); renderCharts();
  }

  function metric(label, value, note) { const a = el('article'); a.append(el('span', '', label), el('strong', '', value)); if (note) a.append(el('small', '', note)); return a; }
  function renderSummary() { const s = state.result.summary, h = document.querySelector('#pfSummary'); h.replaceChildren(); [['总销售额',money(s.totalRevenue)],['广告销售额',money(s.totalAdSales)],['自然销售额',money(s.organicSales)],['广告花费',money(s.totalAdSpend)],['净利润',money(s.netProfit)],['净利润率',pct(s.netMargin)],['整体 ACoS',pct(s.acos)],['整体 TACoS',pct(s.tacos)],['盈利 SKU',String(s.profitableSkus)],['亏损 SKU',String(s.lossMakingSkus)]].forEach(x=>h.append(metric(...x))); }
  function renderHealth() { const h=document.querySelector('#pfHealth'), data=state.result.health; h.replaceChildren(); [['healthy','Healthy'],['warning','Warning'],['critical','Critical'],['no-ads','No Ads'],['no-data','No Data']].forEach(([k,l])=>{const a=metric(l,String(data[k]));a.classList.add(k);h.append(a);}); }
  function renderQuality() { const q=state.result.quality,h=document.querySelector('#pfQuality'); h.replaceChildren(); const list=el('ul'); [['SKUs processed',q.skusProcessed],['Rows imported',q.rowsImported],['Missing Ad Sales',q.missingAdSales],['Missing Ad Spend',q.missingAdSpend],['Missing Product Cost',q.missingProductCost],['Missing Amazon Fees',q.missingAmazonFees],['Duplicate SKUs merged',q.duplicateSkusMerged],['Validation warnings',q.warnings.length]].forEach(x=>{const li=el('li');li.append(el('span','',x[0]),el('b','',String(x[1])));list.append(li);}); h.append(el('strong','','Data Quality'),list); if(q.warnings.length){const d=el('details');d.append(el('summary','',`查看 ${q.warnings.length} 条警告`));q.warnings.slice(0,100).forEach(w=>d.append(el('p','',w)));h.append(d);} }
  function updateMarketplaces(){const select=document.querySelector('#pfMarketplace'); const current=select.value; [...select.querySelectorAll('option:not(:first-child)')].forEach(o=>o.remove()); [...new Set(state.result.items.map(i=>i.marketplace).filter(Boolean))].sort().forEach(m=>select.append(new Option(m,m))); if([...select.options].some(o=>o.value===current))select.value=current;}
  const statusText={strong:'Strong',healthy:'Healthy',low:'Low Margin',loss:'Loss',unknown:'Unknown','no-ads':'No Ads','no-data':'No Data',warning:'Warning',critical:'Critical',complete:'完整',partial:'部分','ads-only':'仅广告','sales-only':'仅销售'};
  const columns=[['profitabilityStatus','Status'],['sku','SKU'],['asin','ASIN'],['productName','Product'],['unitsSold','Units'],['totalSales','Total Sales'],['adSales','Ad Sales'],['organicSales','Organic Sales'],['adSpend','Ad Spend'],['acos','ACoS'],['tacos','TACoS'],['breakEvenAcos','Break-even ACoS'],['operatingCost','Operating Costs'],['netProfit','Net Profit'],['netMargin','Net Margin'],['profitLeakAmount','Profit Leak'],['profitLeakPriority','Risk'],['dataCompleteness','数据完整性']];
  function renderTable(){const head=document.querySelector('#pfHead');head.replaceChildren();columns.forEach(([k,l])=>{const th=el('th');const b=el('button','',l+(state.sort.key===k?(state.sort.direction==='desc'?' ↓':' ↑'):''));b.type='button';b.onclick=()=>{state.sort={key:k,direction:state.sort.key===k&&state.sort.direction==='desc'?'asc':'desc'};renderTable();};th.append(b);head.append(th);}); const all=Engine.filterAndSort(state.result.items,{query:state.query,marketplace:state.marketplace,profitability:state.profitability,health:state.health,leak:state.leak},state.sort);const pages=Math.max(1,Math.ceil(all.length/state.pageSize));state.page=Math.min(state.page,pages);const shown=all.slice((state.page-1)*state.pageSize,state.page*state.pageSize);const body=document.querySelector('#pfBody');body.replaceChildren();shown.forEach(i=>{const tr=el('tr');columns.forEach(([k])=>{let v=i[k];if(['totalSales','adSales','organicSales','adSpend','operatingCost','netProfit','profitLeakAmount'].includes(k))v=money(v);else if(['acos','tacos','breakEvenAcos','netMargin'].includes(k))v=pct(v);else if(statusText[v])v=statusText[v];const td=el('td','',v==null||v===''?'—':String(v));if(k==='profitabilityStatus'||k==='profitLeakPriority')td.className=`tag ${i.profitabilityStatus} ${i.profitLeakPriority}`;tr.append(td);});body.append(tr);});const pager=document.querySelector('#pfPager');pager.replaceChildren(el('span','',`共 ${all.length} 个 SKU · ${state.page} / ${pages}`));const prev=el('button','pf-button secondary','上一页'),next=el('button','pf-button secondary','下一页');prev.disabled=state.page===1;next.disabled=state.page===pages;prev.onclick=()=>{state.page--;renderTable();};next.onclick=()=>{state.page++;renderTable();};pager.append(prev,next);}
  function renderLeaks(){const l=state.result.leakOverview,h=document.querySelector('#pfLeakOverview');h.replaceChildren();[['可量化利润流失',money(l.totalIdentifiedLeak)],['广告超支',money(l.advertisingLeak)],['亏损 SKU 损失',money(l.negativeMarginLoss)],['受影响 SKU',String(l.affectedSkus)]].forEach(x=>h.append(metric(...x)));}
  function renderCharts(){state.charts.forEach(c=>c.destroy());state.charts=[];if(!root.Chart)return;const top=[...state.result.items].sort((a,b)=>(b.totalSales||0)-(a.totalSales||0)).slice(0,10);const opts={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}};state.charts.push(new root.Chart(document.querySelector('#pfRevenueChart'),{type:'bar',data:{labels:top.map(i=>i.sku),datasets:[{label:'Revenue',data:top.map(i=>i.totalSales),backgroundColor:'#4f8a67'},{label:'Net Profit',data:top.map(i=>i.netProfit),backgroundColor:'#d1a24a'}]},options:opts}));const ads=top.filter(i=>i.acos!=null||i.breakEvenAcos!=null);state.charts.push(new root.Chart(document.querySelector('#pfAcosChart'),{type:'bar',data:{labels:ads.map(i=>i.sku),datasets:[{label:'Actual ACoS',data:ads.map(i=>i.acos),backgroundColor:'#c96555'},{label:'Break-even ACoS',data:ads.map(i=>i.breakEvenAcos),backgroundColor:'#35735a'}]},options:opts}));state.charts.push(new root.Chart(document.querySelector('#pfTacosChart'),{type:'bar',data:{labels:top.map(i=>i.sku),datasets:[{label:'TACoS',data:top.map(i=>i.tacos),backgroundColor:'#617b91'}]},options:opts}));}

  function downloadTemplate(){const csv='sku,asin,productName,marketplace,unitsSold,totalSales,adSales,adSpend,productCost,fbaFees,referralFees,storageFees,returnCost,otherCosts\nSKU-A,B0DEMOA,虚构收纳产品,US,100,3999,1600,480,1000,500,600,40,80,30\nSKU-B,B0DEMOB,虚构厨房产品,US,60,2399,1500,600,900,350,360,30,60,20\nSKU-C,B0DEMOC,虚构桌面产品,US,40,1599,0,0,500,230,240,25,30,15';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));a.download='sku-profitability-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function bind(){const input=document.querySelector('#pfInput'),drop=document.querySelector('#pfDrop');drop.onclick=()=>input.click();drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');if(e.dataTransfer.files[0])parseFile(e.dataTransfer.files[0]);};input.onchange=()=>input.files[0]&&parseFile(input.files[0]);document.querySelector('#pfTemplate').onclick=downloadTemplate;document.querySelector('#pfCostMode').onchange=e=>{state.costMode=e.target.value;if(state.rows.length)run();};document.querySelector('#pfPeriodStart').onchange=e=>state.periodStart=e.target.value;document.querySelector('#pfPeriodEnd').onchange=e=>state.periodEnd=e.target.value;document.querySelector('#pfSearch').oninput=e=>{state.query=e.target.value;state.page=1;renderTable();};[['#pfMarketplace','marketplace'],['#pfProfitFilter','profitability'],['#pfHealthFilter','health'],['#pfLeakFilter','leak']].forEach(([id,key])=>document.querySelector(id).onchange=e=>{state[key]=e.target.value;state.page=1;renderTable();});document.querySelector('#pfReset').onclick=()=>{if(!confirm('确定清空当前浏览器中的经营分析数据吗？'))return;state.rows=[];state.result=null;state.charts.forEach(c=>c.destroy());document.querySelector('#pfResults').hidden=true;document.querySelector('#pfEmpty').hidden=false;document.querySelector('#pfReset').hidden=true;document.querySelector('#pfFile').textContent='尚未选择文件';input.value='';};}
  function mount(host){host.innerHTML=markup();bind();}
  function unmount(){state.charts.forEach(c=>c.destroy());state.charts=[];}
  root.ProfitabilityModule={mount,unmount};
})(typeof globalThis !== 'undefined' ? globalThis : this);
