(function(root){
  'use strict';
  const XLSX=root.XLSX;
  const titleStyle={font:{bold:true,sz:16,color:{rgb:'FFFFFF'}},fill:{fgColor:{rgb:'1E5A45'}},alignment:{horizontal:'center'}};
  const headerStyle={font:{bold:true,color:{rgb:'FFFFFF'}},fill:{fgColor:{rgb:'36745B'}},alignment:{horizontal:'center'},border:{bottom:{style:'thin',color:{rgb:'B9C9C1'}}}};
  const labelStyle={font:{bold:true,color:{rgb:'244B3D'}},fill:{fgColor:{rgb:'EAF3EE'}}};
  const profitStyle={font:{bold:true,color:{rgb:'185E3E'}},fill:{fgColor:{rgb:'DDF2E6'}}};
  const lossStyle={font:{bold:true,color:{rgb:'9D2E26'}},fill:{fgColor:{rgb:'FBE3E0'}}};
  const percentFmt='0.00%';
  const moneyFmt='#,##0.00;[Red]-#,##0.00';
  const rateFmt='0.0000';
  function aoa(rows,widths){const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=widths.map(w=>({wch:w}));ws['!freeze']={xSplit:0,ySplit:2};return ws;}
  function styleRow(ws,row,start,end,style){for(let c=start;c<=end;c++){const ref=XLSX.utils.encode_cell({r:row,c});if(ws[ref])ws[ref].s=style;}}
  function formatColumns(ws,rows,percentCols=[],moneyCols=[]){for(let r=0;r<rows.length;r++){percentCols.forEach(c=>{const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell&&typeof cell.v==='number')cell.z=percentFmt;});moneyCols.forEach(c=>{const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell&&typeof cell.v==='number')cell.z=moneyFmt;});}}
  function localAndCny(value,result){return[value,value==null?null:value*result.exchangeRate];}
  function summaryRows(s){const r=s.result,fx=s.exchangeRate,dual=r.currency!=='CNY';const rows=[['Amazon FBA 产品利润分析报告'],['生成时间',new Date(s.generatedAt)],['Amazon站点',r.marketplace],['Marketplace Currency',r.currency],['Exchange Rate',r.exchangeRate],['Exchange Rate Source',fx.source],['Exchange Rate Date',fx.date||'—'],[],dual?['指标',r.currency,'CNY参考值']:['指标','CNY']];const push=(label,value)=>rows.push(dual?[label,...localAndCny(value,r)]:[label,value]);push('销售单价',r.input.sellingPrice);push('折扣后成交价',r.discountedSellingPrice);push('税前收入',r.revenueBeforeTax);push('VAT',r.vat);push('净销售收入',r.netRevenue);push('毛利润',r.grossProfitLocal);rows.push(['毛利率',r.grossMargin/100]);push('广告前利润',r.profitBeforeAdvertising);push('广告成本',r.advertisingCost);push('单件净利润',r.netProfitLocal);rows.push(['净利润率',r.netMargin/100]);rows.push(['ROI',r.roi/100]);rows.push(['盈亏平衡 ACoS',r.breakEvenAcos/100]);push('盈亏平衡 CPC',r.breakEvenCpc);push('盈亏平衡售价',r.breakEvenSellingPrice);rows.push(dual?['最大可承受产品成本',r.breakEvenProductCostLocal,r.breakEvenProductCostCny]:['最大可承受产品成本',r.breakEvenProductCostCny]);push('最大可承受广告成本',r.breakEvenAdvertisingCost);rows.push(['目标 ACoS',r.targetAcos==null?null:r.targetAcos/100]);rows.push(['广告安全缓冲（百分点）',r.advertisingSafetyMargin]);return rows;}
  function buildSummarySheet(s){const rows=summaryRows(s),dual=s.result.currency!=='CNY',ws=aoa(rows,dual?[30,18,18]:[30,18]);ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:dual?2:1}}];styleRow(ws,0,0,dual?2:1,titleStyle);styleRow(ws,8,0,dual?2:1,headerStyle);for(let r=9;r<rows.length;r++){const label=rows[r][0];for(let c=1;c<rows[r].length;c++){const cell=ws[XLSX.utils.encode_cell({r,c})];if(!cell||typeof cell.v!=='number')continue;cell.z=['毛利率','净利润率','ROI','盈亏平衡 ACoS','目标 ACoS'].includes(label)?percentFmt:moneyFmt;}if(label==='单件净利润'||label==='净利润率'||label==='ROI')styleRow(ws,r,0,dual?2:1,s.result.netProfitLocal>=0?profitStyle:lossStyle);}ws.B2.z='yyyy-mm-dd hh:mm';ws.B5.z=rateFmt;return ws;}
  function buildInputsSheet(s){const i=s.input,r=s.result,fx=s.exchangeRate;const rows=[['输入参数'],['字段','数值','单位/币种','说明'],['Amazon站点',i.marketplace,'',''],['站点币种',r.currency,'',''],['汇率',i.exchangeRate,`1 ${r.currency} = X CNY`,fx.mode],['汇率来源',fx.source,'',''],['汇率日期',fx.date||'—','',''],['销售单价',i.sellingPrice,r.currency,'Marketplace Currency'],['折扣率',i.discountRate/100,'%',''],['VAT税率',i.vatRate/100,'%',''],['销售价是否含VAT',i.includesVat?'是':'否','',''],['Referral Fee Rate',i.referralRate/100,'%',''],['产品成本',i.productCost,'CNY',''],['包装成本',i.packagingCost,'CNY',''],['贴标成本',i.labelingCost,'CNY',''],['验货成本',i.inspectionCost,'CNY',''],['工具/模具摊销',i.toolingAmortization,'CNY',''],['国际运费',i.freight,'CNY',''],['关税',i.duty,'CNY',''],['报关/清关费',i.customsClearance,'CNY',''],['FBA配送费',i.fbaFee,r.currency,'Marketplace Currency'],['仓储成本',i.storageCost,r.currency,'Marketplace Currency'],['其他变动成本',i.otherVariableCost,r.currency,'Marketplace Currency'],['退货率',i.returnRate/100,'%',''],['平均每次退货损失',i.averageLossPerReturn,r.currency,'Marketplace Currency'],['广告计算模式',i.adMode,'',''],['ACoS',i.acos/100,'%',''],['CPC',i.cpc,r.currency,'Marketplace Currency'],['CVR',i.cvr/100,'%',''],['目标ACoS',i.targetAcosInput?i.targetAcosInput/100:null,'%','']];const ws=aoa(rows,[28,18,24,30]);ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:3}}];styleRow(ws,0,0,3,titleStyle);styleRow(ws,1,0,3,headerStyle);for(let r0=2;r0<rows.length;r0++){styleRow(ws,r0,0,0,labelStyle);if(rows[r0][2]==='%'){const c=ws[XLSX.utils.encode_cell({r:r0,c:1})];if(c&&typeof c.v==='number')c.z=percentFmt;}else if(typeof rows[r0][1]==='number')ws[XLSX.utils.encode_cell({r:r0,c:1})].z=moneyFmt;}return ws;}
  function buildCostSheet(s){const r=s.result,keys=[['productCost','产品成本'],['packagingCost','包装成本'],['labelingCost','贴标成本'],['inspectionCost','验货成本'],['toolingAmortization','模具摊销'],['freight','国际运费'],['duty','关税'],['customsClearance','报关/清关费'],['referralFee','Referral Fee'],['fbaFee','FBA配送费'],['storageCost','仓储费'],['advertisingCost','广告成本'],['returnLoss','退货损失'],['otherVariableCost','其他变动成本'],['vat','VAT（税费）']];const rows=[['成本明细'],['成本项目',`${r.currency}金额`,'CNY金额','占销售额比例','分类']];keys.forEach(([k,l])=>{const local=r.unitCosts[k],cny=r.unitCostsCny[k];rows.push([l,local,cny,r.revenueBeforeTax>0?local/r.revenueBeforeTax:null,k==='vat'?'税费':'经营成本']);});rows.push(['总成本',r.totalNonTaxCostLocal+r.vat,(r.totalNonTaxCostLocal+r.vat)*r.exchangeRate,r.revenueBeforeTax>0?(r.totalNonTaxCostLocal+r.vat)/r.revenueBeforeTax:null,'含税费']);rows.push(['净利润',r.netProfitLocal,r.netProfitCny,r.revenueBeforeTax>0?r.netProfitLocal/r.revenueBeforeTax:null,'结果']);const ws=aoa(rows,[28,18,18,18,16]);ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:4}}];styleRow(ws,0,0,4,titleStyle);styleRow(ws,1,0,4,headerStyle);formatColumns(ws,rows,[3],[1,2]);styleRow(ws,rows.length-1,0,4,r.netProfitLocal>=0?profitStyle:lossStyle);return ws;}
  function breakEvenStatus(r){if(r.effectiveAcos==null||r.breakEvenAcos==null)return'无法判断';const gap=r.breakEvenAcos-r.effectiveAcos;if(gap<0)return'亏损风险';if(gap<=Math.max(2,r.breakEvenAcos*.1))return'接近盈亏线';return'安全';}
  function buildBreakEvenSheet(s){const r=s.result;const rows=[['盈亏平衡分析'],['指标',`${r.currency} / 数值`,'CNY参考值','状态'],['盈亏平衡售价',r.breakEvenSellingPrice,r.breakEvenSellingPrice*r.exchangeRate,''],['最大可承受产品成本',r.breakEvenProductCostLocal,r.breakEvenProductCostCny,''],['最大可承受广告成本',r.breakEvenAdvertisingCost,r.breakEvenAdvertisingCost*r.exchangeRate,''],['盈亏平衡 ACoS',r.breakEvenAcos/100,null,breakEvenStatus(r)],['盈亏平衡 CPC',r.breakEvenCpc,r.breakEvenCpc*r.exchangeRate,''],['目标 ACoS',r.targetAcos==null?null:r.targetAcos/100,null,''],['ACoS安全缓冲（百分点）',r.advertisingSafetyMargin,null,breakEvenStatus(r)]];const ws=aoa(rows,[32,20,20,18]);ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:3}}];styleRow(ws,0,0,3,titleStyle);styleRow(ws,1,0,3,headerStyle);formatColumns(ws,rows,[1],[1,2]);[5,7].forEach(rr=>{const c=ws[XLSX.utils.encode_cell({r:rr,c:1})];if(c&&typeof c.v==='number')c.z=percentFmt;});return ws;}
  function buildScenarioSheet(s){const base=s.scenarios.base.result;const rows=[['情景分析'],['情景','Selling Price','Product Cost (CNY)','Freight (CNY)','ACoS','Return Rate','CVR','Net Profit','Net Margin','ROI','Break-even ACoS','Break-even CPC','相对基础情景利润变化','汇率快照']];Object.values(s.scenarios).forEach(x=>rows.push([x.name,x.input.sellingPrice,x.input.productCost,x.input.freight,x.input.acos/100,x.input.returnRate/100,x.input.cvr/100,x.result.netProfitLocal,x.result.netMargin/100,x.result.roi/100,x.result.breakEvenAcos/100,x.result.breakEvenCpc,x.result.netProfitLocal-base.netProfitLocal,x.input.exchangeRate]));const ws=aoa(rows,[16,16,18,16,13,13,13,18,14,14,18,18,22,14]);ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:13}}];styleRow(ws,0,0,13,titleStyle);styleRow(ws,1,0,13,headerStyle);formatColumns(ws,rows,[4,5,6,8,9,10],[1,2,3,7,11,12]);for(let r=2;r<rows.length;r++)styleRow(ws,r,7,9,rows[r][7]>=0?profitStyle:lossStyle);return ws;}
  function buildSensitivitySheet(s){const a=s.sensitivity;const labels={sellingPrice:'销售单价',productCost:'产品成本',freight:'国际运费',acos:'广告成本销售比（ACoS）',returnRate:'退货率'};const rows=[['敏感性分析'],['利润影响最大变量',labels[a.largestImpactVariable]||a.largestImpactVariable],[],['变量','变化','净利润','净利润率','利润变化','影响方向']];a.rows.forEach(x=>rows.push([labels[x.variable]||x.variable,x.label,x.netProfit,x.netMargin/100,x.impact,x.impact<0?'负向':x.impact>0?'正向':'无变化']));const ws=aoa(rows,[30,18,18,16,18,14]);ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:5}}];styleRow(ws,0,0,5,titleStyle);styleRow(ws,3,0,5,headerStyle);formatColumns(ws,rows,[3],[2,4]);return ws;}
  function buildDefinitionsSheet(s){const r=s.result;const rows=[['数据口径'],['项目','定义'],['汇率定义',`1单位${r.currency} = ${r.exchangeRate} CNY`],['VAT公式','含税：成交额 × VAT率 ÷ (1 + VAT率)；未税：成交额 × VAT率'],['毛利润公式','税后净收入 − 产品及到岸成本'],['净利润公式','广告前利润 − 广告成本'],['ACoS定义','广告花费 ÷ 广告归因销售额'],['Break-even ACoS定义','广告前利润 ÷ 广告销售额计算基数'],['CPC/CVR公式','单笔广告成本 = CPC ÷ CVR'],['ROI当前定义','净利润 ÷ 全部非税成本（含广告费）'],['退货损失公式','退货率 × 平均每次退货损失'],[],['免责声明','本报告为经营测算工具，不替代Amazon官方费用账单、财务会计或税务申报。']];const ws=aoa(rows,[28,88]);ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:1}}];styleRow(ws,0,0,1,titleStyle);styleRow(ws,1,0,1,headerStyle);for(let r0=2;r0<rows.length;r0++)styleRow(ws,r0,0,0,labelStyle);return ws;}
  function buildWorkbook(snapshot){if(!XLSX)throw new Error('Excel组件未加载');const wb=XLSX.utils.book_new();wb.Props={Title:'Amazon FBA 产品利润分析报告',Subject:'Amazon Seller Workbench',Author:'Amazon Seller Workbench',CreatedDate:new Date(snapshot.generatedAt)};[['利润摘要',buildSummarySheet(snapshot)],['输入参数',buildInputsSheet(snapshot)],['成本明细',buildCostSheet(snapshot)],['盈亏平衡分析',buildBreakEvenSheet(snapshot)],['情景分析',buildScenarioSheet(snapshot)],['敏感性分析',buildSensitivitySheet(snapshot)],['数据口径',buildDefinitionsSheet(snapshot)]].forEach(([name,ws])=>XLSX.utils.book_append_sheet(wb,ws,name));return wb;}
  function cleanFilename(v){return String(v).replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,'_').slice(0,120);}
  function exportProfitWorkbook(){const snapshot=root.ProfitExportData?.getSnapshot?.();if(!snapshot||!Number.isFinite(snapshot.result?.netProfitLocal))throw new Error('当前没有有效计算结果');const d=new Date(),date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const filename=cleanFilename(`Amazon_FBA_Profit_Analysis_${snapshot.result.marketplace}_${date}.xlsx`);XLSX.writeFile(buildWorkbook(snapshot),filename,{compression:true,cellStyles:true});return filename;}
  function updateButton(button){try{const s=root.ProfitExportData?.getSnapshot?.();button.disabled=!s||!Number.isFinite(s.result?.netProfitLocal);}catch(_){button.disabled=true;}}
  function initialize(){const meta=document.querySelector('#profitToolHeader .tool-header-meta');if(!meta||document.querySelector('#exportProfitExcel'))return;const button=document.createElement('button');button.id='exportProfitExcel';button.type='button';button.className='export-excel-button';button.textContent='导出 Excel 报告';button.onclick=()=>{try{exportProfitWorkbook();}catch(e){alert(`Excel导出失败：${e.message}`);}};meta.append(button);document.querySelector('#profit-form')?.addEventListener('input',()=>updateButton(button));updateButton(button);}
  root.ProfitExcelExporter=Object.freeze({buildWorkbook,buildSummarySheet,buildInputsSheet,buildCostSheet,buildBreakEvenSheet,buildScenarioSheet,buildSensitivitySheet,buildDefinitionsSheet,exportProfitWorkbook});
  initialize();
})(typeof globalThis!=='undefined'?globalThis:this);
