(function(root){
  'use strict';
  const Reports=root.AmazonReportEngine, Profit=root.ProfitabilityEngine, Papa=root.Papa;
  const TYPES={sales:{report:'business-report',schema:'business',title:'销售报表',en:'Business Report',path:'Seller Central → Reports → Business Reports → Detail Page Sales and Traffic by Child Item'},ads:{report:'ads-advertised-product',schema:'ads',title:'广告报表',en:'Advertised Product Report',path:'Amazon Ads Console → Measurement & Reporting → Sponsored ads reports → Advertised Product Report'},payments:{report:'payments',schema:'payments',title:'费用报表',en:'Payments Transaction Report',path:'Seller Central → Reports → Payments → Reports Repository → Transaction / Date Range Report'},costs:{report:'product-cost',schema:'cost',title:'产品成本',en:'Product Cost',path:'上传自己的成本表；支持 SKU / ASIN、Unit Cost、Currency'}};
  const reportState={sales:null,ads:null,payments:null,costs:null};
  const ui={marketplace:'US',period:{start:'',end:''},rate:7.1,fingerprints:new Set(),charts:[],items:[],merge:null};
  const $=s=>document.querySelector(s), money=v=>v==null?'成本数据不完整':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}), pct=v=>v==null?'N/A':`${Number(v).toFixed(2)}%`;
  const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
  function template(){return `<section class="profitability-page amazon-import-page"><header class="profitability-hero"><div><p>ADVERTISING &amp; PROFITABILITY</p><h1>广告与利润分析</h1><span>直接导入 Amazon 原生销售、广告和 Payments 报表，合并 SKU / ASIN 后生成经营利润分析。</span></div><div class="privacy-badge">🔒 经营数据仅在当前浏览器本地解析，不会上传到服务器。</div></header>
  <section class="pf-card"><div class="pf-heading"><b>00</b><div><h2>Analysis Period &amp; Marketplace</h2><p>请确保所有上传报表使用相同日期范围和同一站点。</p></div></div><div class="period-grid"><label>开始日期<input id="amzStart" type="date"></label><label>结束日期<input id="amzEnd" type="date"></label><label>Amazon站点<select id="amzMarketplace"></select></label><label>站点币种<input id="amzCurrency" readonly></label><label>1站点币种 = CNY<input id="amzRate" type="number" min="0.0001" step="0.0001"></label></div><div id="amzPeriodWarning" class="pf-note">请设置分析周期，并确保销售、广告及费用报表使用相同日期范围。</div></section>
  <section class="pf-card"><div class="pf-heading"><b>01</b><div><h2>Amazon 数据导入</h2><p>系统自动识别报表；同类型新文件默认替换旧文件，不重复累加。</p></div><button id="costTemplate" class="pf-button secondary">下载“成本CSV模板”</button></div><div id="amzCards" class="amazon-upload-grid"></div><button id="clearAmazon" class="pf-button danger">清除全部分析数据</button></section>
  <div id="amazonEmpty" class="pf-empty"><strong>上传任意一类 Amazon 报表开始分析</strong><span>四份文件不是必需同时上传；数据不足时会明确标记。</span></div>
  <div id="amazonResults" hidden><section class="pf-card"><div class="pf-heading"><b>02</b><div><h2>Data Matching &amp; Quality</h2><p>未匹配 SKU 不会丢弃。</p></div></div><div id="amzWarnings"></div><div id="amzQuality" class="pf-metrics"></div></section>
  <section class="pf-card"><div class="pf-heading"><b>03</b><div><h2>Portfolio Overview</h2><p>组合百分比按汇总金额计算，不平均 SKU 百分比。</p></div></div><div id="amzPortfolio" class="pf-metrics"></div></section>
  <section class="pf-card"><div class="pf-heading"><b>04</b><div><h2>Advertising Health</h2><p>ACoS 衡量广告效率；TACoS 衡量整个 SKU 对广告的依赖。</p></div></div><div id="amzHealth" class="pf-health"></div><div class="pf-note">广告销售使用 Amazon 归因窗口，可能与 Business Report 销售日期不完全一致，因此 ACoS/TACoS 为经营分析口径，不等同财务结算口径。<strong id="amzWindow"></strong></div></section>
  <section class="pf-card"><div class="pf-heading"><b>05</b><div><h2>SKU Profitability</h2><p>完整成本数据存在时才显示完整净利润与 Break-even ACoS。</p></div></div><div class="pf-filters"><input id="amzSearch" type="search" placeholder="搜索 SKU / ASIN"><select id="amzCompleteness"><option value="all">全部完整性</option><option value="full">完整利润</option><option value="profit-partial">部分利润</option><option value="ads-only">广告分析</option><option value="sales-only">销售分析</option></select></div><div class="pf-table-wrap"><table><thead><tr><th>状态</th><th>SKU</th><th>ASIN</th><th>Units</th><th>Revenue</th><th>Ad Sales</th><th>Organic</th><th>Spend</th><th>ACoS</th><th>TACoS</th><th>成本</th><th>Amazon Fees</th><th>Net Profit</th><th>Net Margin</th><th>Break-even ACoS</th><th>Profit Leak</th></tr></thead><tbody id="amzBody"></tbody></table></div></section>
  <section class="pf-card"><div class="pf-heading"><b>06</b><div><h2>Profit Leak</h2><p>只量化有明确数学依据的广告超支与负利润损失。</p></div></div><div id="amzLeaks" class="pf-metrics four"></div></section>
  <section class="pf-card"><div class="pf-heading"><b>07</b><div><h2>Charts</h2><p>收入/利润和 ACoS 盈亏线。</p></div></div><div class="pf-charts"><article><h3>Revenue vs Net Profit</h3><canvas id="amzRevenueChart"></canvas></article><article><h3>ACoS vs Break-even ACoS</h3><canvas id="amzAcosChart"></canvas></article></div></section>
  <section class="pf-card"><div class="pf-heading"><b>08</b><div><h2>公式与数据口径</h2></div></div><div class="pf-formulas"><p><b>Product Cost Total</b>Unit Cost × Units Sold；CNY 成本按站点币种/CNY汇率换算。</p><p><b>Amazon Fees</b>Referral + FBA + Storage + Return + Other Amazon Fees。</p><p><b>Net Profit</b>Total Sales − Product Cost Total − Amazon Fees − Ad Spend。</p><p><b>ACoS / TACoS</b>Ad Spend ÷ Ad Sales / Total Sales。</p><p><b>Break-even ACoS</b>Profit Before Ads ÷ Ad Sales。</p><p><b>费用优先级</b>Actual Payment Data；当前阶段不自动估算 Amazon Fee。</p></div></section></div></section>`;}
  function card(key){const c=TYPES[key],a=node('article','amazon-upload-card');a.dataset.key=key;a.innerHTML=`<div><strong>${c.title}</strong><span>${c.en}</span></div><p>${c.path}</p><button class="amazon-drop" type="button"><b>点击上传或拖放 CSV</b><small>未上传</small></button><input type="file" accept=".csv,text/csv" hidden><div class="amazon-card-status">未上传</div><details><summary>如何从 Amazon 下载？</summary><p>${c.path} → 设置相同日期区间 → Download CSV</p></details><div class="amazon-map-host"></div><div class="amazon-preview"></div>`;const input=a.querySelector('input'),drop=a.querySelector('.amazon-drop');drop.onclick=()=>input.click();input.onchange=()=>input.files[0]&&readFile(input.files[0],key,a);drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])readFile(e.dataTransfer.files[0],key,a)};if(key==='costs'){const d=node('details','amazon-manual-cost');d.innerHTML='<summary>手动补充单个 SKU 成本</summary><div><input data-manual="sku" placeholder="SKU"><input data-manual="asin" placeholder="ASIN（可选）"><input data-manual="cost" type="number" min="0" step="0.01" placeholder="Unit Cost"><select data-manual="currency"><option>CNY</option><option>USD</option><option>GBP</option><option>EUR</option><option>CAD</option><option>AUD</option><option>JPY</option></select><button class="pf-button" type="button">添加 / 更新</button></div>';d.querySelector('button').onclick=()=>{const sku=d.querySelector('[data-manual="sku"]').value.trim(),asin=d.querySelector('[data-manual="asin"]').value.trim(),unitCost=Number(d.querySelector('[data-manual="cost"]').value),costCurrency=d.querySelector('[data-manual="currency"]').value;if(!sku&&!asin)return alert('请填写 SKU 或 ASIN');if(!Number.isFinite(unitCost)||unitCost<0)return alert('请填写有效 Unit Cost');const existing=reportState.costs?.items||[],items=existing.filter(x=>!(sku&&x.sku===sku)&&!(asin&&x.asin===asin));items.push({sku,asin,unitCost,costCurrency});reportState.costs={ok:true,type:'product-cost',items,headers:[],mapping:{},missing:[],warnings:[],meta:{currencies:[],periodStarts:[],periodEnds:[]},fileName:'手动成本',rows:items.length,columns:4};renderCardsStatus();analyze();};a.append(d);}return a;}
  async function fingerprint(file,text){const bytes=new TextEncoder().encode(text.slice(0,200000));const hash=await crypto.subtle.digest('SHA-256',bytes);return`${file.name}:${file.size}:${file.lastModified}:${[...new Uint8Array(hash)].slice(0,8).map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
  function parseCsv(file){return new Promise((resolve,reject)=>Papa.parse(file,{header:true,skipEmptyLines:true,complete:resolve,error:reject}));}
  async function readFile(file,slot,cardEl){const text=await file.text(),fp=await fingerprint(file,text);if(ui.fingerprints.has(fp)&&!confirm('该报表可能已导入，是否替换？'))return;let parsed;try{parsed=await parseCsv(file);}catch(e){return setStatus(cardEl,`解析失败：${e.message}`,'warn');}const headers=parsed.meta.fields||Object.keys(parsed.data[0]||{}),detected=Reports.detectReportType(headers),expected=TYPES[slot].report;setStatus(cardEl,`${file.name} · ${parsed.data.length} 行 · 检测：${detected}`,(detected==='unknown'||detected!==expected)?'warn':'ok');renderPreview(cardEl,parsed.data.slice(0,5),headers);const target=Object.keys(TYPES).find(k=>TYPES[k].report===detected)||slot;const normalized=normalize(target,parsed.data,{});if(!normalized.ok){renderMapping(cardEl,target,parsed.data,headers,normalized.mapping);return;}ui.fingerprints.add(fp);reportState[target]={...normalized,fileName:file.name,fingerprint:fp,rows:parsed.data.length,columns:headers.length,preview:parsed.data.slice(0,5)};if(target!==slot)setStatus(cardEl,`已自动归入：${TYPES[target].title}`,'ok');renderCardsStatus();analyze();}
  function normalize(slot,rows,mapping){return slot==='sales'?Reports.normalizeBusinessReport(rows,mapping):slot==='ads'?Reports.normalizeAdsReport(rows,mapping):slot==='payments'?Reports.normalizePaymentsReport(rows,mapping):Reports.normalizeCostReport(rows,mapping);}
  function renderMapping(cardEl,slot,rows,headers,current){const host=cardEl.querySelector('.amazon-map-host');host.replaceChildren();const box=node('div','pf-map');box.append(node('strong','','需要字段映射'));const schema=TYPES[slot].schema,mapping=current.mapping||Reports.mappingFor(headers,schema);Object.keys(Reports.ALIASES[schema]).forEach(field=>{const l=node('label');l.append(node('span','',field));const s=node('select');s.dataset.field=field;s.append(new Option('未提供',''));headers.forEach(h=>s.append(new Option(h,h)));s.value=mapping[field]||'';l.append(s);box.append(l);});const b=node('button','pf-button','应用字段映射');b.onclick=()=>{const m={};box.querySelectorAll('select').forEach(s=>m[s.dataset.field]=s.value||null);const n=normalize(slot,rows,m);if(!n.ok)return alert(`仍缺少：${n.missing.join('、')}`);reportState[slot]={...n,fileName:'手动映射文件',rows:rows.length,columns:headers.length,preview:rows.slice(0,5)};host.replaceChildren();renderCardsStatus();analyze();};box.append(b);host.append(box);}
  function renderPreview(cardEl,rows,headers){const h=cardEl.querySelector('.amazon-preview');h.replaceChildren();const d=node('details');d.append(node('summary','',`预览前 ${rows.length} 行 · ${headers.length} 列`));const wrap=node('div','amazon-preview-scroll'),table=node('table'),thead=node('thead'),tr=node('tr');headers.slice(0,8).forEach(x=>tr.append(node('th','',x)));thead.append(tr);table.append(thead);const tb=node('tbody');rows.forEach(r=>{const row=node('tr');headers.slice(0,8).forEach(k=>row.append(node('td','',String(r[k]??''))));tb.append(row)});table.append(tb);wrap.append(table);d.append(wrap);h.append(d);}
  function setStatus(cardEl,text,kind){const s=cardEl.querySelector('.amazon-card-status');s.textContent=text;s.className=`amazon-card-status ${kind}`;}
  function renderCardsStatus(){Object.keys(TYPES).forEach(k=>{const c=document.querySelector(`.amazon-upload-card[data-key="${k}"]`),r=reportState[k];if(r){setStatus(c,`✓ 已识别 · ${r.fileName} · ${r.items.length} SKUs · ${r.rows} 行 · ${r.columns||0} 列 · 警告 ${(r.warnings||[]).length}`,(r.warnings||[]).length?'warn':'ok');c.querySelector('.amazon-drop small').textContent=r.fileName;}});}
  function analyze(){const cfg=root.MarketplaceConfig.getMarketplace(ui.marketplace),merged=Reports.mergeAmazonReports({business:reportState.sales,ads:reportState.ads,payments:reportState.payments,costs:reportState.costs,marketplace:ui.marketplace,marketplaceCurrency:cfg.currency,exchangeRates:{[`${cfg.currency}/CNY`]:ui.rate},period:ui.period});ui.merge=merged;ui.items=merged.items.map(x=>Profit.calculate(x));$('#amazonEmpty').hidden=ui.items.length>0;$('#amazonResults').hidden=!ui.items.length;if(!ui.items.length)return;renderAll();}
  function metric(label,value,note){const a=node('article');a.append(node('span','',label),node('strong','',value));if(note)a.append(node('small','',note));return a;}
  function renderAll(){renderQuality();renderPortfolio();renderHealth();renderTable();renderLeaks();renderCharts();}
  function renderQuality(){const q=ui.merge.quality,h=$('#amzQuality');h.replaceChildren();[['Business SKUs',q.businessSkus],['Ads SKUs',q.adsSkus],['Payments SKUs',q.paymentsSkus],['Cost SKUs',q.costSkus],['Matched SKUs',q.matchedSkus],['Unmatched Sales',q.unmatchedSales],['Unmatched Ads',q.unmatchedAds],['Unmatched Fees',q.unmatchedFees],['Missing Costs',q.missingCosts]].forEach(x=>h.append(metric(x[0],String(x[1]))));const w=$('#amzWarnings');w.replaceChildren();[...ui.merge.warnings,...ui.items.flatMap(i=>i.warnings||[])].forEach(x=>w.append(node('div','pf-note',x)));$('#amzWindow').textContent=ui.merge.attributionWindow?` 广告归因窗口：${ui.merge.attributionWindow==='14d'?'14天':'7天'}`:' 广告归因窗口：未识别';}
  function totals(){const sum=f=>ui.items.reduce((s,i)=>s+(i[f]||0),0),revenue=sum('totalSales'),adSales=sum('adSales'),spend=sum('adSpend'),profitValues=ui.items.filter(i=>i.netProfit!=null);return{revenue,adSales,spend,organic:ui.items.every(i=>i.organicSales!=null)?sum('organicSales'):null,profit:profitValues.length===ui.items.length?sum('netProfit'):null,acos:adSales>0?spend/adSales*100:null,tacos:revenue>0?spend/revenue*100:null,margin:revenue>0&&profitValues.length===ui.items.length?sum('netProfit')/revenue*100:null};}
  function renderPortfolio(){const t=totals(),h=$('#amzPortfolio');h.replaceChildren();[['Revenue',money(t.revenue)],['Ad Sales',money(t.adSales)],['Organic Sales',t.organic==null?'周期/归因需检查':money(t.organic)],['Ad Spend',money(t.spend)],['Net Profit',money(t.profit)],['Net Margin',pct(t.margin)],['Portfolio ACoS',pct(t.acos)],['Portfolio TACoS',pct(t.tacos)]].forEach(x=>h.append(metric(...x)));}
  function renderHealth(){const h=$('#amzHealth');h.replaceChildren();['healthy','warning','critical','no-ads','no-data'].forEach(k=>{const count=ui.items.filter(i=>i.advertisingHealth===k).length;h.append(metric(k==='no-ads'?'No Ads':k==='no-data'?'No Data':k[0].toUpperCase()+k.slice(1),String(count)));h.lastChild.classList.add(k)});}
  const compText={full:'完整利润','profit-partial':'部分利润','ads-only':'广告分析','sales-only':'销售分析'};
  function renderTable(){const q=($('#amzSearch')?.value||'').toLowerCase(),filter=$('#amzCompleteness')?.value||'all',body=$('#amzBody');body.replaceChildren();ui.items.filter(i=>(!q||`${i.sku} ${i.asin}`.toLowerCase().includes(q))&&(filter==='all'||i.dataCompleteness===filter)).slice(0,1000).forEach(i=>{const tr=node('tr');const values=[compText[i.dataCompleteness]||i.dataCompleteness,i.sku||'—',i.asin||'—',i.unitsSold??'—',money(i.totalSales),money(i.adSales),i.organicSales==null?'N/A':money(i.organicSales),money(i.adSpend),pct(i.acos),pct(i.tacos),money(i.productCost),money(i.amazonFees),money(i.netProfit),pct(i.netMargin),pct(i.breakEvenAcos),money(i.profitLeakAmount)];values.forEach(v=>tr.append(node('td','',String(v))));body.append(tr);});}
  function renderLeaks(){const sum=f=>ui.items.reduce((s,i)=>s+(i[f]||0),0),h=$('#amzLeaks'),affected=ui.items.filter(i=>i.leaks?.length).length;h.replaceChildren();[['可量化利润流失',money(sum('profitLeakAmount'))],['广告超支',money(sum('advertisingLeak'))],['负利润损失',money(sum('negativeMarginLoss'))],['受影响 SKU',String(affected)]].forEach(x=>h.append(metric(...x)));}
  function renderCharts(){ui.charts.forEach(c=>c.destroy());ui.charts=[];if(!root.Chart)return;const top=[...ui.items].sort((a,b)=>(b.totalSales||0)-(a.totalSales||0)).slice(0,10),opts={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}};ui.charts.push(new root.Chart($('#amzRevenueChart'),{type:'bar',data:{labels:top.map(i=>i.sku||i.asin),datasets:[{label:'Revenue',data:top.map(i=>i.totalSales),backgroundColor:'#4f8a67'},{label:'Net Profit',data:top.map(i=>i.netProfit),backgroundColor:'#d1a24a'}]},options:opts}));ui.charts.push(new root.Chart($('#amzAcosChart'),{type:'bar',data:{labels:top.map(i=>i.sku||i.asin),datasets:[{label:'ACoS',data:top.map(i=>i.acos),backgroundColor:'#c96555'},{label:'Break-even ACoS',data:top.map(i=>i.breakEvenAcos),backgroundColor:'#35735a'}]},options:opts}));}
  function downloadCostTemplate(){const csv='SKU,ASIN,Unit Cost,Currency\nSKU001,B0ABC,40,CNY\nSKU002,B0DEF,8.5,USD';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download='product-cost-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function clearAll(){if(!confirm('确定清除全部销售、广告、费用和成本分析数据吗？'))return;Object.keys(reportState).forEach(k=>reportState[k]=null);ui.fingerprints.clear();ui.items=[];ui.merge=null;ui.charts.forEach(c=>c.destroy());ui.charts=[];mount($('#profitabilityModule'));}
  async function updateRate(){const cfg=root.MarketplaceConfig.getMarketplace(ui.marketplace);$('#amzCurrency').value=cfg.currency;ui.rate=root.MarketplaceConfig.getDefaultExchangeRate(cfg.currency);$('#amzRate').value=ui.rate;try{const s=root.ExchangeRateService?.createService?.();if(s){const r=await s.getLatestRate(cfg.currency);if(r?.rate){ui.rate=r.rate;$('#amzRate').value=r.rate;if(ui.items.length)analyze();}}}catch(_){}}
  function bind(){const cards=$('#amzCards');Object.keys(TYPES).forEach(k=>cards.append(card(k)));const mp=$('#amzMarketplace');Object.values(root.MarketplaceConfig.MARKETPLACES).forEach(m=>mp.append(new Option(m.name,m.code)));mp.value=ui.marketplace;mp.onchange=()=>{ui.marketplace=mp.value;updateRate();if(ui.items.length)analyze();};$('#amzStart').value=ui.period.start;$('#amzEnd').value=ui.period.end;$('#amzStart').onchange=e=>{ui.period.start=e.target.value;$('#amzPeriodWarning').hidden=ui.period.start&&ui.period.end;if(ui.items.length)analyze();};$('#amzEnd').onchange=e=>{ui.period.end=e.target.value;$('#amzPeriodWarning').hidden=ui.period.start&&ui.period.end;if(ui.items.length)analyze();};$('#amzRate').onchange=e=>{ui.rate=Number(e.target.value)||ui.rate;if(ui.items.length)analyze();};$('#costTemplate').onclick=downloadCostTemplate;$('#clearAmazon').onclick=clearAll;$('#amzSearch').oninput=renderTable;$('#amzCompleteness').onchange=renderTable;updateRate();renderCardsStatus();}
  function mount(host){host.innerHTML=template();bind();if(ui.items.length){$('#amazonEmpty').hidden=true;$('#amazonResults').hidden=false;renderAll();}}
  function unmount(){ui.charts.forEach(c=>c.destroy());ui.charts=[];}
  root.ProfitabilityModule={mount,unmount};
})(typeof globalThis!=='undefined'?globalThis:this);
