'use strict';
const assert = require('node:assert/strict');
const Dashboard = require('../dashboard-intelligence');
let passed = 0;
function test(name, fn) { fn(); passed += 1; console.log(`PASS ${name}`); }
function item(id, category, overrides) { return Object.assign({ id, priority:'medium', category, newsCategory:'fba', title:id, explanation:'Summary', whyItMatters:'Relevant for your marketplace.', marketplaces:['US'], affectedModules:['inventory'], recommendedAction:null, actionType:null, urgency:'upcoming', impactLevel:'medium', effectiveAt:'2026-10-01', daysRemaining:11, sourceNewsIds:[id], sourceCount:1, reasonCodes:[], confidence:'high' }, overrides || {}); }
function deps(brief, profile) { return { SellerIntelligence:{ evaluateAll(news) { return news.map(id => ({ news:{ id } })); } }, DecisionModel:{ buildDailyBrief() { return brief; } }, SellerProfile:{ getProfile() { return profile || { configured:true, marketplaces:['US'] }; } } }; }
function baseBrief(parts) { return Object.assign({ generatedAt:'2026-09-20T00:00:00.000Z', actions:[], risks:[], monitor:[], opportunities:[], diagnostics:{ hiddenReasonCounts:{ UNKNOWN_RELEVANCE:2 } } }, parts || {}); }
const news = { getLatestNews() { return ['a','b','c','d','e','f']; } };

test('0 decision returns the specified empty state', () => { const model=Dashboard.buildDecisionDashboardModel(news,deps(baseBrief())); assert.equal(model.emptyState.message,'今天暂无需要优先处理的 Amazon 变化。'); assert.equal(model.summary.total,0); });
test('summary is computed from final decision categories', () => { const model=Dashboard.buildDecisionDashboardModel(news,deps(baseBrief({actions:[item('a','action'),item('b','action')],risks:[item('r','risk')],monitor:[item('m','monitor')]}))); assert.deepEqual(model.summary,{total:4,actions:2,risks:1,monitor:1}); });
test('five displayed cards have a five-item summary total', () => { const values=['a','b','c','d','e','f'].map((id,index)=>item(id,index < 2 ? 'action' : index < 4 ? 'risk' : 'monitor')); const model=Dashboard.buildDecisionDashboardModel(news,deps(baseBrief({actions:values.slice(0,2),risks:values.slice(2,4),monitor:values.slice(4)}))); assert.equal(model.decisions.length,5); assert.equal(model.summary.actions + model.summary.risks + model.summary.monitor,5); });
test('preserves aligned public item fields without creating actions', () => { const value=item('a','risk',{ newsCategory:'compliance', recommendedAction:null, marketplaces:['US','CA'], affectedModules:['profit'], actionType:'read-news', effectiveAt:'2026-09-28', daysRemaining:8, sourceCount:2, confidence:'medium' }); const out=Dashboard.buildDecisionDashboardModel(news,deps(baseBrief({risks:[value]}))).decisions[0]; assert.equal(out.category,'risk'); assert.equal(out.newsCategory,'compliance'); assert.equal(out.recommendedAction,null); assert.deepEqual(out.marketplaces,['US','CA']); assert.deepEqual(out.affectedModules,['profit']); assert.equal(out.actionType,'read-news'); assert.equal(out.effectiveAt,'2026-09-28'); assert.equal(out.sourceCount,2); assert.equal(out.confidence,'medium'); });
test('never uses information or opportunities as Dashboard decisions', () => { const model=Dashboard.buildDecisionDashboardModel(news,deps(Object.assign(baseBrief(),{information:[item('i','information')],opportunities:[item('o','opportunity')]}))); assert.equal(model.decisions.length,0); });
test('profile warning diagnostics and deterministic order are preserved', () => { const brief=baseBrief({actions:[item('a','action')],risks:[item('r','risk')]}); const before=JSON.stringify(brief); const model=Dashboard.buildDecisionDashboardModel(news,deps(brief,{configured:false,marketplaces:[]})); assert.equal(model.profileConfigured,false); assert.equal(model.diagnostics.hiddenReasonCounts.UNKNOWN_RELEVANCE,2); assert.deepEqual(model.decisions.map(x=>x.id),['a','r']); assert.equal(JSON.stringify(brief),before); });
test('gracefully falls back when dependencies are unavailable', () => { const model=Dashboard.buildDecisionDashboardModel(news,{}); assert.equal(model.available,false); assert.equal(model.decisions.length,0); });
console.log(`dashboard decision experience tests passed: ${passed}`);
