'use strict';
const assert = require('node:assert/strict');
const DecisionModel = require('../decision-model');
let passed = 0;
function test(name, fn) { fn(); passed += 1; console.log(`PASS ${name}`); }
function input(id, overrides) {
  const base = { news:{ id, title:`Title ${id}`, summary:`Summary ${id}`, category:'fba', marketplaces:['US'], officialUrl:`https://example.test/${id}`, publishedAt:'2026-09-01', status:'active' }, relevance:{ status:'relevant', reasonCodes:['EXACT_MARKETPLACE_MATCH'], matchedMarketplaces:['US'] }, impact:{ impactLevel:'medium', urgency:'upcoming', affectedModules:['inventory'], actionRequired:false, actionType:null, actionText:'', effectiveAt:'2026-11-01', daysUntilEffective:42, reasonCodes:['AFFECTED_MODULE'], confidence:'high' }, actionState:{ status:'pending' } };
  return Object.assign(base, overrides || {});
}
function brief(items) { return DecisionModel.buildDailyBrief(items, { id:'seller-1', version:'3.0' }, { briefDate:'2026-09-20', timezone:'Asia/Shanghai' }); }
function all(result) { return [...result.actions, ...result.risks, ...result.monitor]; }
function action(id, extra) { const value=input(id); value.impact=Object.assign(value.impact,{ impactLevel:'high', urgency:'effective-soon', actionRequired:true, actionType:'check-inventory', actionText:'Review inventory', effectiveAt:'2026-09-25', daysUntilEffective:5 }); return Object.assign(value, extra || {}); }

test('public DecisionItem exposes the aligned contract only', () => { const item=all(brief([action('one')]))[0]; for (const key of ['id','priority','category','newsCategory','title','explanation','whyItMatters','marketplaces','affectedModules','recommendedAction','actionType','urgency','impactLevel','effectiveAt','daysRemaining','sourceNewsIds','sourceCount','reasonCodes','confidence']) assert.ok(key in item); for (const key of ['affectedMarketplace','relatedModule','supportingModules','mergeCount','rationaleCodes']) assert.equal(key in item,false); });
test('category is only action risk or monitor and news category remains separate', () => { const risk=input('risk'); risk.impact.impactLevel='high'; risk.impact.urgency='active'; const monitor=input('monitor'); const items=all(brief([action('action'),risk,monitor])); assert.deepEqual(items.map(item=>item.category),['action','risk','monitor']); assert.ok(items.every(item=>item.newsCategory==='fba')); });
test('information is absent and low value relevant news is hidden', () => { const low=input('low'); low.impact={ impactLevel:'low', urgency:'active', affectedModules:[], actionRequired:false, actionType:null, actionText:'', effectiveAt:null, daysUntilEffective:null, reasonCodes:[], confidence:'low' }; const result=brief([low]); assert.equal('information' in result,false); assert.equal(all(result).length,0); assert.equal(result.diagnostics.hiddenReasonCounts.LOW_VALUE,1); });
test('uses NewsImpact urgency and days without recalculation', () => { const value=action('overdue'); value.impact.urgency='overdue'; value.impact.daysUntilEffective=37; value.impact.effectiveAt='2030-01-01'; const item=all(brief([value]))[0]; assert.equal(item.urgency,'overdue'); assert.equal(item.daysRemaining,37); assert.equal(item.effectiveAt,'2030-01-01'); });
test('preserves every NewsImpact urgency value', () => { const values=['overdue','effective-soon','upcoming','active','unknown'].map((urgency,index) => { const value=action(`u${index}`); value.impact.urgency=urgency; return value; }); const result=brief(values); assert.deepEqual([...all(result).map(item=>item.urgency)].sort(),['active','effective-soon','overdue','unknown','upcoming'].sort()); });
test('why it matters is seller readable while reason codes retain compatibility code', () => { const value=action('profile'); value.relevance={ status:'relevant', reasonCodes:['PROFILE_NOT_CONFIGURED_COMPATIBILITY'], matchedMarketplaces:[] }; const item=all(brief([value]))[0]; assert.equal(item.reasonCodes.includes('PROFILE_NOT_CONFIGURED_COMPATIBILITY'),true); assert.equal(item.whyItMatters.includes('PROFILE_NOT_CONFIGURED_COMPATIBILITY'),false); assert.match(item.whyItMatters,/尚未配置卖家站点/); });
test('preserves marketplaces modules action type and confidence', () => { const value=action('fields'); value.relevance.matchedMarketplaces=['US','CA']; value.impact.affectedModules=['inventory','profit']; value.impact.confidence='medium'; const item=all(brief([value]))[0]; assert.deepEqual(item.marketplaces,['US','CA']); assert.deepEqual(item.affectedModules,['inventory','profit']); assert.equal(item.actionType,'check-inventory'); assert.equal(item.confidence,'medium'); });
test('keeps official effectiveAt source count and exact deduplication', () => { const a=action('same'); const b=action('same'); const result=brief([a,b]); const item=all(result)[0]; assert.equal(item.effectiveAt,'2026-09-25'); assert.equal(item.sourceCount,1); assert.equal(result.diagnostics.hiddenReasonCounts.DUPLICATE,1); });
test('completed actions and irrelevant news stay out of the brief', () => { const done=action('done'); done.actionState.status='completed'; const ignored=action('ignored'); ignored.relevance={ status:'irrelevant', reasonCodes:[], matchedMarketplaces:[] }; const result=brief([done,ignored]); assert.equal(all(result).length,0); assert.equal(result.diagnostics.hiddenReasonCounts.COMPLETED,1); assert.equal(result.diagnostics.hiddenReasonCounts.IRRELEVANT,1); });
test('caps the only three decision sections at five', () => { const result=brief(['a','b','c','d','e','f'].map(action)); assert.equal(all(result).length,5); assert.equal(result.actions.length + result.risks.length + result.monitor.length,5); assert.equal(result.diagnostics.hiddenReasonCounts.LOWER_PRIORITY,1); });
test('does not mutate its input', () => { const value=action('immutable'); const before=JSON.stringify(value); brief([value]); assert.equal(JSON.stringify(value),before); });
console.log(`decision model tests passed: ${passed}`);
