'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),E=require('../knowledge-answer-engine'),C=require('../knowledge-answer-contracts');
const q={question:'q',normalizedQuestion:'q',scope:{resolvedMarketplaces:[],regions:[]}},clone=x=>JSON.parse(JSON.stringify(x));
const bundle={claimId:'c',sufficiency:{status:'conflicted'},candidates:[{candidateId:'a',retrievalItemId:'a',sourceId:'government'},{candidateId:'b',retrievalItemId:'b',sourceId:'amazon-seller-help'}],assessments:[{assessmentId:'a1',candidateId:'a',supportStatus:'supports',admissible:true,evidenceRole:'supporting'},{assessmentId:'b1',candidateId:'b',supportStatus:'contradicts',evidenceRole:'conflicting'}],conflicts:[{conflictId:'real-conflict',type:'support-vs-contradiction',assessmentIds:['a1','b1']}],verifications:[],diagnostics:{}};
const out=E.answer(q,[{claimId:'c',text:'c'}],[bundle],{fakeCitation:{citationId:'cite-fake',sourceId:'fake'}});assert.deepEqual(out.conflictNotes[0].citationIds,['cite-a','cite-b']);assert.equal(out.citations.some(c=>c.citationId==='cite-fake'),false);assert.equal(out.citations.every(c=>['a','b'].includes(c.retrievalItemId)),true);assert.equal(C.validateStructuredAnswer(out).valid,true);
const production=['knowledge-answer-engine.js','knowledge-answer-planner.js','knowledge-answer-grounding.js','knowledge-answer-citations.js','knowledge-answer-limitations.js','knowledge-grounded-composer.js'],forbidden=/require\(['"](?:axios|http|https|node:http|node:https)|\bfetch\s*\(|retrieval-executor|live-adapters|\bllm\b/i;for(const file of production)assert.equal(forbidden.test(fs.readFileSync(path.join(__dirname,'..',file),'utf8')),false,file);assert.match(fs.readFileSync(path.join(__dirname,'..','knowledge-answer-engine.js'),'utf8'),/knowledge-answer-grounding/);
const deep={claimId:'deep',candidates:[{candidateId:'candidate-deep',retrievalItemId:'retrieval-deep',sourceId:'s',providerId:'p',externalId:'e',title:'t',url:'https://x',publisher:'pub',author:'author',publishedAt:'2026-01-01',effectiveAt:'2026-02-01',retrievedAt:'2026-03-01',metadata:{provenance:{nested:true}}}],verifications:[{status:'supports',metadata:{nested:true}}],assessments:[{assessmentId:'assessment-deep',claimId:'deep',candidateId:'candidate-deep',admissible:true,evidenceRole:'supporting',metadata:{nested:true}}],conflicts:[],sufficiency:{status:'sufficient'},diagnostics:{nested:{value:1}}};const claims=[{claimId:'deep',text:'Real claim',scope:{nested:true},metadata:{nested:true},marketplaces:['US'],regions:[],temporalRequirement:{mode:'current'}}],bs=clone(deep),cs=clone(claims),deepOut=E.answer(q,claims,[deep],{});assert.deepStrictEqual(deep,bs);assert.deepStrictEqual(claims,cs);assert.equal(Object.hasOwn(deep,'claim'),false);assert.notEqual(deep.candidates[0].candidateId,deep.candidates[0].retrievalItemId);assert.equal(deepOut.officialFacts[0].text,'Real claim');assert.equal(deepOut.citations[0].retrievalItemId,'retrieval-deep');assert.deepEqual(deepOut.citations[0].candidateIds,['candidate-deep']);
const missing=E.answer(q,[],[deep],{}),limit=missing.limitations.find(x=>x.type==='missing-claim-text');assert.equal(missing.officialFacts.length,0);for(const key of ['statementId','statementType','limitationId','type','claimIds','text','message','groundingRefs','citationIds','relatedAssessmentIds','metadata'])assert.ok(Object.hasOwn(limit,key));assert.equal(limit.text.includes('deep'),false);for(const items of [missing.officialFacts,missing.derivedConclusions,missing.accountSpecificFindings,missing.conflictNotes])assert.equal(items.some(x=>x.text==='deep'),false);
for(const status of ['insufficient','conflicted']){const o=E.answer(q,[],[{claimId:'z',sufficiency:{status},candidates:[],assessments:[],conflicts:[],diagnostics:{}}],{});assert.equal(/[0-9]|https?:\/\//.test(o.shortAnswer),false);assert.equal(o.shortAnswer.includes('fee'),false);}
console.log('answer integration passed');
