'use strict';

const assert = require('node:assert/strict');
const Adapter = require('../knowledge-deepseek-claim-verifier');
const Core = require('../knowledge-production-claim-verifier');
const response = (status, body) => ({ status, async json() { return body; } });
const responseFor = value => ({ output: [{ content: [{ type: 'output_text', text: JSON.stringify(value) }] }] });
function payload() { return { claim: { claimId: 'c', text: 'Vine Pre-Launch 的定义。', marketplaces: ['US'], regions: [], temporalRequirement: { mode: 'current' }, requestedYear: '2026', authorityRequirement: { mustInclude: ['amazon-official'] } }, evidence: { title: 'Amazon', text: 'Vine Pre-Launch allows enrollment before a product formally launches.', snippet: null, url: 'https://sellercentral.amazon.com/help/vine', sourceId: 'amazon-seller-help', providerId: 'amazon-seller-help-provider', publisher: null, publishedAt: null, effectiveAt: null }, context: { now: '2026-09-28T00:00:00.000Z' } }; }
function proposal(overrides = {}) { return { status: 'supports', supportStrength: 'direct', excerpt: 'allows enrollment before a product formally launches', rationale: 'direct', verifierType: 'ignored', metadata: {}, ...overrides }; }
function claim() { return { claimId: 'c', text: 'Vine Pre-Launch 的定义。', claimType: 'definition', topic: 'fba-logistics', intent: 'definition', marketplaces: ['US'], regions: [], requestedYear: '2026', freshness: 'current', authorityRequirement: { mustInclude: ['amazon-official'] }, temporalRequirement: { mode: 'current' }, metadata: {} }; }
function candidate() { return { candidateId: 'candidate', claimId: 'c', retrievalItemId: 'item', sourceId: 'amazon-seller-help', providerId: 'amazon-seller-help-provider', url: 'https://sellercentral.amazon.com/help/vine', externalId: null, title: 'Amazon', content: 'Vine Pre-Launch allows enrollment before a product formally launches.', excerpt: null, publishedAt: null, effectiveAt: null }; }
async function run() {
  assert.equal(Adapter.DEFAULT_ENDPOINT, 'https://api.deepseek.com/responses'); assert.equal(Adapter.DEFAULT_MODEL, 'deepseek-flash'); assert.throws(() => Adapter.createDeepSeekClaimVerifierAdapter(), /DEEPSEEK_API_KEY_REQUIRED/);
  let call; const source = payload(); const snapshot = structuredClone(source); const adapter = Adapter.createDeepSeekClaimVerifierAdapter({ apiKey: ' deepseek-secret ', endpoint: 'https://test.invalid/responses', fetchImpl: async (url, options) => { call = { url, options }; return response(200, responseFor(proposal())); } });
  const result = await adapter.verifyImpl(source); assert.deepEqual(source, snapshot); assert.equal(call.url, 'https://test.invalid/responses'); assert.equal(call.options.headers.Authorization, 'Bearer deepseek-secret'); const body = JSON.parse(call.options.body); assert.equal(body.model, 'deepseek-flash'); assert.deepEqual(body.reasoning, { effort: 'none' }); assert.equal(body.text.format.strict, true); assert.equal(Object.hasOwn(body, 'tools'), false); assert.match(body.input[1].content[0].text, /Vine Pre-Launch/); assert.deepEqual(result.metadata, { provider: 'deepseek', model: 'deepseek-flash' });
  for (const item of [proposal({ status: 'contradicts' }), proposal({ status: 'not-addressed', supportStrength: 'none', excerpt: null }), proposal({ status: 'unclear', supportStrength: 'indirect' }), proposal({ status: 'unknown', supportStrength: 'unknown', excerpt: null })]) assert.equal((await Adapter.createDeepSeekClaimVerifierAdapter({ apiKey: 'x', fetchImpl: async () => response(200, responseFor(item)) }).verifyImpl(payload())).status, item.status);
  for (const [status, code] of [[401, 'DEEPSEEK_VERIFIER_AUTH_ERROR'], [403, 'DEEPSEEK_VERIFIER_AUTH_ERROR'], [429, 'DEEPSEEK_VERIFIER_RATE_LIMITED'], [500, 'DEEPSEEK_VERIFIER_SERVICE_UNAVAILABLE']]) await assert.rejects(() => Adapter.createDeepSeekClaimVerifierAdapter({ apiKey: 'x', fetchImpl: async () => response(status, {}) }).verifyImpl(payload()), error => error.code === code);
  for (const failure of [async () => { throw Error('network'); }, async () => { const error = Error('abort'); error.name = 'AbortError'; throw error; }]) await assert.rejects(() => Adapter.createDeepSeekClaimVerifierAdapter({ apiKey: 'x', fetchImpl: failure }).verifyImpl(payload()), error => /^DEEPSEEK_VERIFIER_(NETWORK_ERROR|TIMEOUT)$/.test(error.code));
  for (const invalidResponse of [{}, { output_text: 'not-json' }, { output: [{ content: [{ type: 'refusal' }] }] }]) await assert.rejects(() => Adapter.createDeepSeekClaimVerifierAdapter({ apiKey: 'x', fetchImpl: async () => response(200, invalidResponse) }).verifyImpl(payload()), error => /^DEEPSEEK_VERIFIER_(INVALID_RESPONSE|REFUSED)$/.test(error.code));
  let verified = await Core.createProductionClaimVerifier({ verifyImpl: adapter.verifyImpl }).verify(claim(), candidate(), {}); assert.deepEqual([verified.status, verified.excerpt], ['supports', 'allows enrollment before a product formally launches']); verified = await Core.createProductionClaimVerifier({ verifyImpl: Adapter.createDeepSeekClaimVerifierAdapter({ apiKey: 'x', fetchImpl: async () => response(200, responseFor(proposal({ excerpt: 'fabricated' }))) }).verifyImpl }).verify(claim(), candidate(), {}); assert.deepEqual([verified.status, verified.metadata.errorCode], ['unknown', 'VERIFIER_EXCERPT_NOT_FOUND']);
  console.log('knowledge deepseek claim verifier passed');
}
run().catch(error => { console.error(error); process.exitCode = 1; });
